package com.example.justbirthday.localDatabaseInteraction;

import java.util.List;

import localDatabase.tables.FriendsData;

public class AddFriends implements Runnable{
    List<FriendsData> friendsData;
    DatabaseManager databaseManager;

    public AddFriends(List<FriendsData> friendsData, DatabaseManager databaseManager) {
        this.friendsData = friendsData;
        this.databaseManager = databaseManager;
    }

    @Override
    public void run() {
        // This should not generate errors, since table key is autogenerated.
        databaseManager.insertAllFriends(friendsData);
    }
}
